- name: task1_1
  hosts: node1.example.com

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Starting web server
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Creating a file with content
    copy:
      dest: /var/www/html/index.html
      content: |
        Welcome to my web server

  - name: permit traffic in default zone for https service
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled



