- name: task1_2
  hosts: node1.example.com

  tasks:
  - name: Uninstall httpd
    yum:
      name: httpd
      state: removed

  - name: Deleting file with content
    file:
      state: absent
      path: /var/www/html/index.html

  - name: do not permit traffic in default zone for https service
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: disabled
